### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by Swarzox** [ArikReuter/TopicGPT#3]
Hi there,

I'm trying to use the TopicGPT library in my Python project, but I'm encountering a ModuleNotFoundError when running my code. Here's the relevant part of the error traceback:

Traceback (most recent call last):
  File "/path/to/project/main.py", line 9, in <module>
    from topicgpt.TopicGPT import TopicGPT
  File "/path/to/project/env/lib/python3.12/site-packages/topicgpt/TopicGPT.py", line 14, in <module>
    from Clustering import Clustering_and_DimRed
ModuleNotFoundError: No module named 'Clustering'

I'm using Python 3.12 on macOS.

**Comment by belonel** [comment]
I had the same issue caused by the openai update. From 1.0.0 version embeddings_utils [was removed](https://community.openai.com/t/where-is-the-original-openai-embeddings-utils-in-the-latest-version/479854). Import in one of the files was causing error above. 

Try: 
pip uninstall openai
pip install openai==0.28.1

**Comment by lagefreitas** [comment]
hi @belonel ! Thank you for sharing this `pip install openai==0.28.1` hint. It worked for me too. But I had to reinstall topicgpt  too:

```bash
pip uninstall topicgpt
pip uninstall openai
pip install openai==0.28.1
pip install topicgpt
```

**Comment by ezecarrascosa** [comment]
Hi,
I wanted to use the library but wihile importing it I am getting the error:
File i:\ds\aiitsm-backend.venv\Lib\site-packages\hdbscan\plots.py:8
6 import numpy as np
----> 8 from scipy.cluster.hierarchy import dendrogram
9 from sklearn.manifold import TSNE
...
---> 14 from Clustering import Clustering_and_DimRed
15 from ExtractTopWords import ExtractTopWords
16 from TopwordEnhancement import TopwordEnhancement

ModuleNotFoundError: No module named 'Clustering'

I saw the other issues suggesting to intall the version of openAI==0.28.1. But within my project I cannot lower the version of openAi less than 1.40.1.

is there any other way to fix this import issue?
